### ISSUE TITLE
Pay to pass bug

### ISSUE THREAD

**Issue by Htminhduc** [ofekmiz/Habitica-Pomodoro-SiteKeeper#9] opened 2020-03-31 10:53 UTC
Can you change it so that the extension doesn't eat all of my coin in pay to pass mode. Make it notifies me every time I use all the time I bought, so that I can decide whether to pay for more time or just stop.

**Comment by ofekmiz** [comment] 2020-03-31 12:06
Hi! thanks for the feedback. I'm not sure what do you mean? If the extension charge you too much coins (more than what you chose) please try to uninstall and reinstall the extension. let me know if it worked :)

**Comment by Htminhduc** [comment] 2020-03-31 12:15
Thank you for answering me.
The problem is when I paid to pass and used up all of my time (I set it to 3 gold for 60 minutes), the extension did not notify me. It automatically charged me 3 gold and give me 60 mins. If you can, please make it notify me, so I don't use all of my gold and not knowing it.

**Comment by ofekmiz** [comment] 2020-03-31 12:43
@Htminhduc  You suppose to see this screen before paying:
![image](https://user-images.githubusercontent.com/39601942/78027608-4df54700-7366-11ea-99bd-cc9e99b61f23.png)

can you see it?

**Comment by Htminhduc** [comment] 2020-04-01 03:57
Yes, I see it every First time I try to pay. The problem is: as i use Reddit for more than 60 min, the extension automatically grant me another 60 min, eat 3 gold, without notifying me.

**Comment by ofekmiz** [comment] 2020-04-01 04:06
Got it, Thanks. I'll investigate the issue

**Comment by ofekmiz** [comment] 2020-04-06 01:03
The issue is fixed! the new version will be available soon

**Comment by Htminhduc** [comment] 2020-04-08 15:45
thank you, but now i found a new bug, just for you=))

**Comment by ofekmiz** [comment] 2020-04-09 15:50
Lol, what is it? , by the way, is the issue fixed in version 5.1? (PUBLISHED TODAY)

**Comment by ofekmiz** [comment] 2020-04-12 02:58
Fixed in version 5.2

**Closed** 2020-04-12 02:58 UTC
Labels: Bug, Priority : High, Testing ✔
