### ISSUE TITLE
Why blocked web pages will be repeatedly reopened every few minutes

### ISSUE THREAD

**Issue by xuli500177** [ofekmiz/Habitica-Pomodoro-SiteKeeper#8] opened 2020-03-29 08:46 UTC
Thanks for your extension! it is really helpful!
But I found that when I browse to blocked web pages, they will be repeatedly reopened every few minutes, depending on the Pass Duration that I set. And sometimes it will reopen several webpages and deduct goals multiple times in Habitica. Even if I close the blocked page, it will reopen it until I start the next Pomodoro. So I have to fix the Character Value in Habitica every few minutes. It is quite inconvenient so I think this could be a bug in this wonderful extension.
Btw, my operating system is Mac OS 10.15.2, and my browser is Chrome  80.0.3987.149.
It is so appreciated if you can fix this bug! 😁

**Comment by ofekmiz** [comment] 2020-03-29 09:07
Sorry for all the bugs lately, google change their privacy policy and I had
to change many things really quick, so naturally bugs poped 😥
I Just uploaded a new version that will be available soon (version 5).
Let me know if the issue is fixed in this version ☺

**Comment by xuli500177** [comment] 2020-03-29 09:40
Oh I see, sounds like a really huge workload.😂 Thanks for your work so much! No need to be too hurry I can use its main function for now. Really appreciate!

**Comment by ofekmiz** [comment] 2020-03-29 09:44
lol, thanks. I use the extension myself and wish to fix it quick too 😆

**Comment by xuli500177** [comment] 2020-03-31 09:25
Thanks for your update! This extension is working well on my computer now!

However, there is small feedback: Whether it is possible to add a notification sound when the pom ran over? Sometimes I am focusing on my book rather than the screen, so I won't know the pom time is out without a sound alert. How about an app notification like Break Extension Start alert? Or a sound notice in Chrome?

Anyhow, this is the most excellent Chrome Extension I've ever used! Thank you😁

**Comment by ofekmiz** [comment] 2020-03-31 11:15
Great! Thanks for the update

Actually there are sound notifications :)
You need to make sure you enable chrome naitive notifications. This is how
you do it on windows:
https://m.youtube.com/watch?v=cFM0CStbjTU

**Comment by ofekmiz** [comment] 2020-03-31 12:02
@xuli500177 by the way you can also enable mobile notifications! enable it in the advanced setting and than you will get a private message from yourself in habitica (that has mobile notifications if enabled in habitica app) when break extension starts and when pomodoro ends

**Comment by xuli500177** [comment] 2020-03-31 14:16
<img width="271" alt="截屏2020-03-3122 12 23" src="https://user-images.githubusercontent.com/62830942/78036616-1a81df00-739d-11ea-834f-d3dc7cbba150.png">
Thank for your reply! 😁

But I have enabled chrome native notifications accordingly, and I can receive the notifications. What I mean is this notification has no sound, which means you have to look at the screen to notice it, otherwise you will ignore it. Just provide a small recommendation, because I think many people run the Pomodoro for reading books instead of always focusing on the screen.

Moreover, when it comes to the app notification. I have already set it in the advanced setting and I have received Break Extension Start alert. 
But I haven't received a notification when pom ends. And I can't find that setting in the advanced setting. Here are the screenshots.
<img width="807" alt="截屏2020-03-3122 12 04" src="https://user-images.githubusercontent.com/62830942/78036598-12c23a80-739d-11ea-9b24-8dab75bd2c79.png">

**Comment by ofekmiz** [comment] 2020-03-31 17:59
You are right, I might add mobile notification for that too! thanks for the
great idea, if you can open a new feature request it be great :)

**Comment by diamondduck** [comment] 2020-04-02 15:32
It looks like the bug still persists for me. I reinstalled the extension.

**Comment by ofekmiz** [comment] 2020-04-02 15:35
OK, thanks for the updae. if you can send me a screen recording it would really help!

**Comment by diamondduck** [comment] 2020-04-02 15:47
I will try. My os is ubuntu 18.04,  google chrome version: Google Chrome 80.0.3987.149

**Comment by ofekmiz** [comment] 2020-04-06 01:04
Thanks for the screenshot!
The issue is fixed :) the new version will be available soon

**Closed** 2020-04-09 15:51 UTC
Labels: Bug, Priority : High, Testing
